### ISSUE TITLE
Can mainline kernel source be used for Lineage OS (Sony Z5C)?

### ISSUE THREAD

**Issue by fpemud** [Professor-Berni/android_kernel_sony_msm8994#2]
I know that msm8894 has been mainlined (refer to this [link](https://github.com/torvalds/linux/blob/master/arch/arm64/boot/dts/qcom/msm8992.dtsi)).

Can I use the mainline kernel source to build Lineage OS for the Sony Z5 Compact, or is this specific kernel tree mandatory?

**Comment by Professor-Berni** [comment]
I have not managed to compile Torvalds' kernel for the Z5C.
